#!/usr/bin/env bash
set -euo pipefail
cd /home/sharwa/sharwa_ai

echo "=== 0) sanity: repo root ==="
pwd
git rev-parse --show-toplevel

echo "=== 1) write patch_sessions.py (surgical, anchor-based - aborts loudly on any mismatch) ==="
base64 -d > /tmp/patch_sessions.py <<'B64EOF'
aW1wb3J0IHBhdGhsaWIsIHN5cywgcmUKCnAgPSBwYXRobGliLlBhdGgoc3lzLmFyZ3ZbMV0gaWYg
bGVuKHN5cy5hcmd2KSA+IDEgZWxzZSAiZ2F0ZXdheS9zcmMvc2Vzc2lvbnMuanMiKQpzcmMgPSBw
LnJlYWRfdGV4dCgpCm9yaWcgPSBzcmMKY3JsZiA9ICdcclxuJyBpbiBzcmMgICMgbWF0Y2gvcmVw
bGFjZSB0b2xlcmFudCBvZiBDUkxGLCBpbiBjYXNlIHRoZSBmaWxlIChvcgogICAgICAgICAgICAg
ICAgICAgICAgICAjIGp1c3QgdGhpcyByZWdpb24pIHVzZXMgV2luZG93cyBsaW5lIGVuZGluZ3Mg
LSBhCiAgICAgICAgICAgICAgICAgICAgICAgICMgbGl0ZXJhbCAnXG4nLW9ubHkgYW5jaG9yIHdv
dWxkIHNpbGVudGx5IGZhaWwgdG8KICAgICAgICAgICAgICAgICAgICAgICAgIyBtYXRjaCBhICdc
clxuJyBmaWxlIGV2ZW4gdGhvdWdoIHRoZSB0ZXh0IGlzCiAgICAgICAgICAgICAgICAgICAgICAg
ICMgb3RoZXJ3aXNlIGlkZW50aWNhbC4KCgpkZWYgZmluZF9hbmRfcmVwbGFjZSh0ZXh0LCBhbmNo
b3IsIHJlcGxhY2VtZW50LCBsYWJlbCk6CiAgICAiIiJDUkxGLXRvbGVyYW50IGV4YWN0LXRleHQg
cmVwbGFjZTogYW5jaG9yL3JlcGxhY2VtZW50IGFyZSB3cml0dGVuIHdpdGgKICAgIHBsYWluICdc
bic7IG1hdGNoaW5nIGFsbG93cyBhbiBvcHRpb25hbCAnXHInIGJlZm9yZSBlYWNoICdcbicgc28g
dGhpcwogICAgd29ya3Mgd2hldGhlciB0aGUgZmlsZSB1c2VzIExGIG9yIENSTEYsIGFuZCB0aGUg
cmVwbGFjZW1lbnQgaXMgZW1pdHRlZAogICAgaW4gd2hpY2hldmVyIHN0eWxlIHRoZSBmaWxlIGFs
cmVhZHkgdXNlcy4iIiIKICAgIHBhdHRlcm4gPSByZS5lc2NhcGUoYW5jaG9yKS5yZXBsYWNlKHIn
XG4nLCByJ1xyP1xuJykKICAgIG0gPSByZS5zZWFyY2gocGF0dGVybiwgdGV4dCkKICAgIGlmIG5v
dCBtOgogICAgICAgIHJldHVybiBOb25lCiAgICByZXAgPSByZXBsYWNlbWVudC5yZXBsYWNlKCdc
clxuJywgJ1xuJykKICAgIGlmIGNybGY6CiAgICAgICAgcmVwID0gcmVwLnJlcGxhY2UoJ1xuJywg
J1xyXG4nKQogICAgcmV0dXJuIHRleHRbOm0uc3RhcnQoKV0gKyByZXAgKyB0ZXh0W20uZW5kKCk6
XQoKCiMgLS0tIDEpIGltcG9ydCAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0KaW1wb3J0X2FuY2hvciA9ICJpbXBvcnQgeyBjb25maWcgfSBm
cm9tICcuL2NvbmZpZy5qcyc7IgppZiAiZnJvbSAnLi9tZWRpYS5qcyciIGluIHNyYzoKICAgIHBy
aW50KCJtZWRpYS5qcyBpbXBvcnQgYWxyZWFkeSBwcmVzZW50LCBza2lwcGluZyIpCmVsc2U6CiAg
ICBuZXdfc3JjID0gZmluZF9hbmRfcmVwbGFjZSgKICAgICAgICBzcmMsIGltcG9ydF9hbmNob3Is
CiAgICAgICAgaW1wb3J0X2FuY2hvciArICJcbmltcG9ydCB7IGRvd25sb2FkQW5kVXBsb2FkTWVk
aWEgfSBmcm9tICcuL21lZGlhLmpzJzsiLAogICAgICAgICJpbXBvcnQiLAogICAgKQogICAgaWYg
bmV3X3NyYyBpcyBOb25lOgogICAgICAgIHJhaXNlIFN5c3RlbUV4aXQoIkFCT1JUOiBjb25maWcg
aW1wb3J0IGFuY2hvciBub3QgZm91bmQgaW4gc2Vzc2lvbnMuanMgLSByZWZ1c2luZyB0byBndWVz
cy1lZGl0LiBObyBjaGFuZ2VzIHdyaXR0ZW4uIikKICAgIHNyYyA9IG5ld19zcmMKCiMgLS0tIDIp
IGlzTWVkaWE6IGFkZCBzdGlja2VyIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0KaXNtZWRpYV9hbmNob3IgPSAiICBjb25zdCBpc01lZGlhID0gZW50cnkudHlwZSA9
PT0gJ2ltYWdlJyB8fCBlbnRyeS50eXBlID09PSAnYXVkaW8nIHx8IGVudHJ5LnR5cGUgPT09ICd2
aWRlbycgfHwgZW50cnkudHlwZSA9PT0gJ2RvY3VtZW50JzsiCmlzbWVkaWFfbmV3ID0gIiAgY29u
c3QgaXNNZWRpYSA9IGVudHJ5LnR5cGUgPT09ICdpbWFnZScgfHwgZW50cnkudHlwZSA9PT0gJ2F1
ZGlvJyB8fCBlbnRyeS50eXBlID09PSAndmlkZW8nIHx8IGVudHJ5LnR5cGUgPT09ICdkb2N1bWVu
dCcgfHwgZW50cnkudHlwZSA9PT0gJ3N0aWNrZXInOyIKaWYgaXNtZWRpYV9uZXcucmVwbGFjZSgi
ICIsICIiKSBpbiBzcmMucmVwbGFjZSgiICIsICIiKS5yZXBsYWNlKCJcciIsICIiKToKICAgIHBy
aW50KCJpc01lZGlhIGFscmVhZHkgaW5jbHVkZXMgc3RpY2tlciwgc2tpcHBpbmciKQplbHNlOgog
ICAgbmV3X3NyYyA9IGZpbmRfYW5kX3JlcGxhY2Uoc3JjLCBpc21lZGlhX2FuY2hvciwgaXNtZWRp
YV9uZXcsICJpc01lZGlhIikKICAgIGlmIG5ld19zcmMgaXMgTm9uZToKICAgICAgICByYWlzZSBT
eXN0ZW1FeGl0KCJBQk9SVDogaXNNZWRpYSBhbmNob3Igbm90IGZvdW5kIGluIHNlc3Npb25zLmpz
IC0gcmVmdXNpbmcgdG8gZ3Vlc3MtZWRpdC4gTm8gY2hhbmdlcyB3cml0dGVuLiIpCiAgICBzcmMg
PSBuZXdfc3JjCgojIC0tLSAzKSBtZWRpYSBoYW5kbGluZyBibG9jayAtLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQpibG9ja19hbmNob3IgPSAiIiIgIGlmIChpc01l
ZGlhKSB7CiAgICBjb25zdCB7IGRvd25sb2FkRm4gPSBkb3dubG9hZE1lZGlhVG9CdWZmZXIsIHVw
bG9hZEZuID0gdXBsb2FkVG9NaW5pbyB9ID0gZGVwczsKICAgIGNvbnN0IG1lZGlhID0gZGV0ZWN0
TWVkaWEobXNnKTsKICAgIGNvbnN0IGV4dCA9IGV4dGVuc2lvbkZvcihtZWRpYS5jb250ZW50KTsK
ICAgIGNvbnN0IG9iamVjdEtleSA9IG1lZGlhT2JqZWN0S2V5KHNlc3Npb25JZCwgZXh0KTsKICAg
IGNvbnN0IGNvbnRlbnRUeXBlID0gKG1lZGlhLmNvbnRlbnQubWltZXR5cGUgfHwgJycpLnNwbGl0
KCc7JylbMF0udHJpbSgpIHx8ICdhcHBsaWNhdGlvbi9vY3RldC1zdHJlYW0nOwogICAgdHJ5IHsK
ICAgICAgY29uc3QgYnVmZmVyID0gYXdhaXQgZG93bmxvYWRGbihtc2cpOwogICAgICBhd2FpdCB1
cGxvYWRXaXRoUmV0cnkoYnVmZmVyLCBvYmplY3RLZXksIGNvbnRlbnRUeXBlLCB1cGxvYWRGbik7
CiAgICAgIGVudHJ5Lm1lZGlhLm9iamVjdF9rZXkgPSBvYmplY3RLZXk7CiAgICB9IGNhdGNoIChl
cnIpIHsKICAgICAgbG9nZ2VyLmVycm9yKHsgc2Vzc2lvbklkLCBtZXNzYWdlX2lkOiBlbnRyeS5w
cm92aWRlcl9tZXNzYWdlX2lkLCBlcnI6IGVyci5tZXNzYWdlIH0sICdbc2Vzc2lvbnNdIG1lZGlh
IHByb2Nlc3NpbmcgZmFpbGVkJyk7CiAgICAgIGVudHJ5Lm1lZGlhLm9iamVjdF9rZXkgPSBudWxs
OwogICAgICBlbnRyeS5tZWRpYS5mYWlsZWQgPSB0cnVlOwogICAgICBlbnRyeS50ZXh0ID0gJ9iq
2LnYsNmR2LEg2YXYudin2YTYrNipINin2YTZhdix2YHZgiDYp9mE2YXYsdiz2YQuJzsKICAgIH0K
ICB9IiIiCgpibG9ja19uZXcgPSAiIiIgIGlmIChpc01lZGlhKSB7CiAgICBjb25zdCBtZWRpYSA9
IGRldGVjdE1lZGlhKG1zZyk7CiAgICBjb25zdCBleHQgPSBleHRlbnNpb25Gb3IobWVkaWEuY29u
dGVudCk7CiAgICBjb25zdCBjb250ZW50VHlwZSA9IChtZWRpYS5jb250ZW50Lm1pbWV0eXBlIHx8
ICcnKS5zcGxpdCgnOycpWzBdLnRyaW0oKSB8fCAnYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtJzsK
CiAgICBpZiAoZGVwcy5kb3dubG9hZEZuIHx8IGRlcHMudXBsb2FkRm4pIHsKICAgICAgLy8gTGVn
YWN5IGJ1ZmZlci1iYXNlZCBwYXRoIChQMC4yLWVyYSk6IGtlcHQgb25seSBmb3IgY2FsbGVycy90
ZXN0cyB0aGF0CiAgICAgIC8vIGluamVjdCB0aGUgb2xkLXN0eWxlIGRlcHMuZG93bmxvYWRGbiht
c2cpLT5CdWZmZXIgLyBkZXBzLnVwbG9hZEZuKGJ1ZmZlciwKICAgICAgLy8gb2JqZWN0S2V5LCBj
b250ZW50VHlwZSkgc2hhcGUuIE5ldyBjYWxsZXJzIHNob3VsZCBub3Qgc2V0IHRoZXNlIC0gdGhl
CiAgICAgIC8vIHN0cmVhbWluZyBQMC4zIHBhdGggYmVsb3cgKGRlZmF1bHQpIGlzIHRoZSBwcm9k
dWN0aW9uIHBhdGguCiAgICAgIGNvbnN0IHsgZG93bmxvYWRGbiA9IGRvd25sb2FkTWVkaWFUb0J1
ZmZlciwgdXBsb2FkRm4gPSB1cGxvYWRUb01pbmlvIH0gPSBkZXBzOwogICAgICBjb25zdCBvYmpl
Y3RLZXkgPSBtZWRpYU9iamVjdEtleShzZXNzaW9uSWQsIGV4dCk7CiAgICAgIHRyeSB7CiAgICAg
ICAgY29uc3QgYnVmZmVyID0gYXdhaXQgZG93bmxvYWRGbihtc2cpOwogICAgICAgIGF3YWl0IHVw
bG9hZFdpdGhSZXRyeShidWZmZXIsIG9iamVjdEtleSwgY29udGVudFR5cGUsIHVwbG9hZEZuKTsK
ICAgICAgICBlbnRyeS5tZWRpYS5vYmplY3Rfa2V5ID0gb2JqZWN0S2V5OwogICAgICAgIGVudHJ5
Lm1lZGlhLnN0YXR1cyA9ICdvayc7CiAgICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgIGxvZ2dl
ci5lcnJvcih7IHNlc3Npb25JZCwgbWVzc2FnZV9pZDogZW50cnkucHJvdmlkZXJfbWVzc2FnZV9p
ZCwgZXJyOiBlcnIubWVzc2FnZSB9LCAnW3Nlc3Npb25zXSBtZWRpYSBwcm9jZXNzaW5nIGZhaWxl
ZCcpOwogICAgICAgIGVudHJ5Lm1lZGlhLm9iamVjdF9rZXkgPSBudWxsOwogICAgICAgIGVudHJ5
Lm1lZGlhLmZhaWxlZCA9IHRydWU7CiAgICAgICAgZW50cnkubWVkaWEuc3RhdHVzID0gJ2ZhaWxl
ZCc7CiAgICAgICAgZW50cnkudGV4dCA9ICfYqti52LDZkdixINmF2LnYp9mE2KzYqSDYp9mE2YXY
sdmB2YIg2KfZhNmF2LHYs9mELic7CiAgICAgIH0KICAgIH0gZWxzZSB7CiAgICAgIC8vIFAwLjMg
ZGVmYXVsdDogc3RyZWFtaW5nIGRvd25sb2FkICsgc3RyZWFtaW5nIG11bHRpcGFydCB1cGxvYWQs
IGEKICAgICAgLy8gcGVyLXR5cGUgc2l6ZSBjYXAsIGEgcGVyLXNlc3Npb24gZGFpbHkgcXVvdGEg
b24gcmVkaXMtZHVyYWJsZSwgYW5kCiAgICAgIC8vIG1hZ2ljLWJ5dGUgY29udGVudC10eXBlIHZl
cmlmaWNhdGlvbiAoc2VlIG1lZGlhLmpzKS4gRmFsbHMgYmFjayB0bwogICAgICAvLyB0aGUgc2Ft
ZSBncmFjZWZ1bC1kZWdyYWRhdGlvbiBjb250cmFjdCAob2JqZWN0X2tleSBudWxsLCBmYWlsZWQK
ICAgICAgLy8gdHJ1ZSwgQXJhYmljIGZhbGxiYWNrIHRleHQpIG9uIGFueSByZWplY3Rpb24gb3Ig
ZXJyb3IgLSBuZXZlciB0aHJvd3MKICAgICAgLy8gb3V0IHRvIHRoZSBjYWxsZXIuCiAgICAgIHRy
eSB7CiAgICAgICAgaWYgKCFyZWRpc0NsaWVudCkgdGhyb3cgbmV3IEVycm9yKCdyZWRpcy1kdXJh
YmxlIGNsaWVudCBub3QgY29uZmlndXJlZCcpOwogICAgICAgIGNvbnN0IHJlc3VsdCA9IGF3YWl0
IGRvd25sb2FkQW5kVXBsb2FkTWVkaWEoewogICAgICAgICAgY29udGVudDogbWVkaWEuY29udGVu
dCwKICAgICAgICAgIHR5cGU6IGVudHJ5LnR5cGUsCiAgICAgICAgICBzZXNzaW9uSWQsCiAgICAg
ICAgICBwcm92aWRlck1lc3NhZ2VJZDogZW50cnkucHJvdmlkZXJfbWVzc2FnZV9pZCwKICAgICAg
ICAgIGV4dCwKICAgICAgICAgIG1pbWVUeXBlOiBjb250ZW50VHlwZSwKICAgICAgICAgIHJlZGlz
Q2xpZW50LAogICAgICAgICAgczNDbGllbnQ6IGdldFMzQ2xpZW50KCksCiAgICAgICAgICBidWNr
ZXQ6IHByb2Nlc3MuZW52Lk1JTklPX0JVQ0tFVF9OQU1FLAogICAgICAgICAgZG93bmxvYWRGbjog
ZGVwcy5tZWRpYURvd25sb2FkRm4sCiAgICAgICAgfSk7CiAgICAgICAgZW50cnkubWVkaWEuc3Rh
dHVzID0gcmVzdWx0LnN0YXR1czsKICAgICAgICBpZiAocmVzdWx0LnN0YXR1cyA9PT0gJ29rJykg
ewogICAgICAgICAgZW50cnkubWVkaWEub2JqZWN0X2tleSA9IHJlc3VsdC5vYmplY3Rfa2V5Owog
ICAgICAgIH0gZWxzZSB7CiAgICAgICAgICBlbnRyeS5tZWRpYS5vYmplY3Rfa2V5ID0gbnVsbDsK
ICAgICAgICAgIGVudHJ5Lm1lZGlhLmZhaWxlZCA9IHRydWU7CiAgICAgICAgICBpZiAocmVzdWx0
LnNpemUgIT09IHVuZGVmaW5lZCkgZW50cnkubWVkaWEuc2l6ZSA9IHJlc3VsdC5zaXplOwogICAg
ICAgICAgZW50cnkudGV4dCA9ICfYqti52LDZkdixINmF2LnYp9mE2KzYqSDYp9mE2YXYsdmB2YIg
2KfZhNmF2LHYs9mELic7CiAgICAgICAgICBsb2dnZXIud2Fybih7IHNlc3Npb25JZCwgbWVzc2Fn
ZV9pZDogZW50cnkucHJvdmlkZXJfbWVzc2FnZV9pZCwgc3RhdHVzOiByZXN1bHQuc3RhdHVzIH0s
ICdbc2Vzc2lvbnNdIG1lZGlhIHJlamVjdGVkIChQMC4zKScpOwogICAgICAgIH0KICAgICAgfSBj
YXRjaCAoZXJyKSB7CiAgICAgICAgbG9nZ2VyLmVycm9yKHsgc2Vzc2lvbklkLCBtZXNzYWdlX2lk
OiBlbnRyeS5wcm92aWRlcl9tZXNzYWdlX2lkLCBlcnI6IGVyci5tZXNzYWdlIH0sICdbc2Vzc2lv
bnNdIG1lZGlhIHByb2Nlc3NpbmcgZmFpbGVkJyk7CiAgICAgICAgZW50cnkubWVkaWEub2JqZWN0
X2tleSA9IG51bGw7CiAgICAgICAgZW50cnkubWVkaWEuZmFpbGVkID0gdHJ1ZTsKICAgICAgICBl
bnRyeS5tZWRpYS5zdGF0dXMgPSAnZmFpbGVkJzsKICAgICAgICBlbnRyeS50ZXh0ID0gJ9iq2LnY
sNmR2LEg2YXYudin2YTYrNipINin2YTZhdix2YHZgiDYp9mE2YXYsdiz2YQuJzsKICAgICAgfQog
ICAgfQogIH0iIiIKCmlmICJQMC4zIGRlZmF1bHQ6IHN0cmVhbWluZyBkb3dubG9hZCIgaW4gc3Jj
OgogICAgcHJpbnQoIm1lZGlhIGJsb2NrIGFscmVhZHkgcGF0Y2hlZCwgc2tpcHBpbmciKQplbHNl
OgogICAgbmV3X3NyYyA9IGZpbmRfYW5kX3JlcGxhY2Uoc3JjLCBibG9ja19hbmNob3IsIGJsb2Nr
X25ldywgIm1lZGlhLWJsb2NrIikKICAgIGlmIG5ld19zcmMgaXMgTm9uZToKICAgICAgICAjIERp
YWdub3N0aWMgYWlkOiBzaG93IHdoYXQgSVMgYXJvdW5kICJpc01lZGlhKSB7IiBzbyBhIHJlYWwg
bWlzbWF0Y2gKICAgICAgICAjIChub3QganVzdCBDUkxGKSBjYW4gYmUgc2VlbiBhbmQgZml4ZWQg
d2l0aG91dCBhbm90aGVyIGJsaW5kIGd1ZXNzLgogICAgICAgIGlkeCA9IHNyYy5maW5kKCJpZiAo
aXNNZWRpYSkgeyIpCiAgICAgICAgY29udGV4dCA9IHNyY1ttYXgoMCwgaWR4IC0gNDApOiBpZHgg
KyA3MDBdIGlmIGlkeCAhPSAtMSBlbHNlICIobGl0ZXJhbCAnaWYgKGlzTWVkaWEpIHsnIG5vdCBm
b3VuZCBhdCBhbGwpIgogICAgICAgIHByaW50KCItLS0tLSBERUJVRzogYWN0dWFsIGNvbnRlbnQg
YXJvdW5kIHRoZSBpc01lZGlhIGJsb2NrIC0tLS0tIikKICAgICAgICBwcmludChjb250ZXh0KQog
ICAgICAgIHByaW50KCItLS0tLSBFTkQgREVCVUcgLS0tLS0iKQogICAgICAgIHJhaXNlIFN5c3Rl
bUV4aXQoIkFCT1JUOiBtZWRpYS1oYW5kbGluZyBibG9jayBhbmNob3Igbm90IGZvdW5kIGluIHNl
c3Npb25zLmpzIC0gcmVmdXNpbmcgdG8gZ3Vlc3MtZWRpdC4gTm8gY2hhbmdlcyB3cml0dGVuIChz
ZWUgREVCVUcgYmxvY2sgYWJvdmUpLiIpCiAgICBzcmMgPSBuZXdfc3JjCgppZiBzcmMgPT0gb3Jp
ZzoKICAgIHByaW50KCJubyBjaGFuZ2VzIG5lZWRlZCAoYWxyZWFkeSBwYXRjaGVkKSIpCmVsc2U6
CiAgICBwLndyaXRlX3RleHQoc3JjKQogICAgcHJpbnQoInNlc3Npb25zLmpzIHBhdGNoZWQgT0si
KQo=
B64EOF
python3 --version >/dev/null

echo "=== 2) apply the patch to gateway/src/sessions.js ==="
python3 /tmp/patch_sessions.py gateway/src/sessions.js
node --check gateway/src/sessions.js && echo "sessions.js: syntax OK after patch"

echo "=== 3) hunt_gate (correct path: scripts/hunt_gate.mjs, run from repo root) ==="
node scripts/hunt_gate.mjs || echo "HUNT_GATE_EXIT=$?"

echo "=== 4) fast/hermetic node --test (gateway/, full suite incl. existing media.test.js) ==="
# Run in a subshell so a `cd gateway` here can never leak into the rest of
# the script (a prior version of this script had exactly that bug: if the
# piped test command failed, the trailing `&& cd ..` was skipped under
# set -e/pipefail and every later step silently ran from inside gateway/).
# `|| true` keeps the script going even if a test fails, so the rest of the
# review (docker build/ps, git diff) still runs and you see everything in
# one pass.
( cd gateway && node --test 2>&1 | tail -60 ) || true
pwd

echo "=== 5) rebuild the gateway image (picks up the new sessions.js source) ==="
docker compose build gateway

echo "=== 6) real-redis run (RUN_REAL_REDIS_TESTS=1, bind-mounted src, against the live redis-durable) ==="
docker compose run --rm -e RUN_REAL_REDIS_TESTS=1 \
  -v "$(pwd)/gateway/src:/app/src:ro" \
  gateway node --test src/__tests__/real_redis_integration.test.js

echo "=== 7) confirm the running gateway/gateway-forwarder were not disturbed (NOT restarted by this script) ==="
docker compose ps

echo "=== 8) review before commit (nothing is committed by this script, and the live containers still run the OLD sessions.js until you explicitly restart them) ==="
git status
git diff --stat
git diff gateway/src/sessions.js
