-- =============================================================================
-- Sharwa AI - reference database schema (PostgreSQL 16 + pgvector + PostGIS)
--
-- Purpose: make the architecture's hard guarantees enforceable IN THE DATABASE,
-- so they hold even if application code has a bug:
--   #1  cross-tenant isolation      -> RLS on every tenant table + hash-partitioned vectors
--   #5  idempotency                 -> UNIQUE constraints (inbound_events, outbox, scheduled_jobs)
--   #7  back-in-stock race          -> app.allocate_stock_holds() (row locks, no Redis locks)
--   #11 handoff state machine       -> bot_status/epoch/version writable ONLY via app.handoff_*()
--   #17 durable queues              -> outbox / scheduled_jobs / campaign_recipients + claim functions
--   #20 money                       -> BIGINT minor units + ISO currency, never float
--
-- Roles (created NOLOGIN here; deployment creates LOGIN roles that inherit):
--   sharwa_app     tenant-scoped application role. NOT the table owner => subject to RLS.
--   sharwa_system  cross-tenant system tasks (dispatcher/sweeper/ingest). May ONLY execute the
--                  SECURITY DEFINER functions granted below; has no direct table access.
--
-- Every tenant-scoped transaction MUST begin with:  SET LOCAL app.tenant_id = '<uuid>';
-- (transaction-scoped => safe behind PgBouncer in transaction-pooling mode)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS postgis;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sharwa_app') THEN
    CREATE ROLE sharwa_app NOLOGIN NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'sharwa_system') THEN
    CREATE ROLE sharwa_system NOLOGIN NOBYPASSRLS;
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS app;

-- Tenant context helper. Missing/empty setting => NULL => every RLS predicate is NULL => zero rows.
CREATE OR REPLACE FUNCTION app.current_tenant() RETURNS uuid
LANGUAGE sql STABLE AS
$$ SELECT NULLIF(current_setting('app.tenant_id', true), '')::uuid $$;

-- =============================================================================
-- 1. Tenants, channels, kill switches, staff
-- =============================================================================

CREATE TABLE tenants (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_ref     text NOT NULL UNIQUE,                    -- opaque reference to the platform tenant (NOT schema_name)
  name             text NOT NULL,
  timezone         text NOT NULL DEFAULT 'Asia/Riyadh',     -- drives quiet hours
  default_currency char(3) NOT NULL CHECK (default_currency ~ '^[A-Z]{3}$'),
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended')),
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE channel_accounts (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id),
  type        text NOT NULL CHECK (type IN ('whatsapp_baileys','whatsapp_cloud','instagram','livechat')),
  session_id  text NOT NULL UNIQUE,                         -- opaque, generated by the platform (never by the gateway)
  phone_e164  text,
  engine      text NOT NULL DEFAULT 'django' CHECK (engine IN ('django','ai_core')),  -- strangler switch (risk #25)
  status      text NOT NULL DEFAULT 'unknown'
              CHECK (status IN ('unknown','qr_pending','connected','reconnecting','disconnected','logged_out','conflict','banned')),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON channel_accounts (tenant_id);

-- Kill switches (risk #19). Global rows have NULL scope_id. No RLS: managed by admin API only.
CREATE TABLE kill_switches (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scope      text NOT NULL CHECK (scope IN ('global','tenant','channel_account')),
  scope_id   uuid,
  capability text NOT NULL CHECK (capability IN
             ('*','ai_reply','marketing','broadcast','geocode_auto','gift','fit','checkout','back_in_stock','media')),
  state      text NOT NULL CHECK (state IN ('on','degraded','off')),
  reason     text,
  set_by     text NOT NULL,
  set_at     timestamptz NOT NULL DEFAULT now(),
  CHECK ((scope = 'global') = (scope_id IS NULL)),
  UNIQUE NULLS NOT DISTINCT (scope, scope_id, capability)
);

-- Most restrictive of (global, tenant, channel) x (capability, '*') wins: off > degraded > on.
CREATE OR REPLACE FUNCTION app.effective_switch(p_tenant uuid, p_channel uuid, p_capability text)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT COALESCE(
    (SELECT CASE max(CASE state WHEN 'off' THEN 2 WHEN 'degraded' THEN 1 ELSE 0 END)
              WHEN 2 THEN 'off' WHEN 1 THEN 'degraded' ELSE 'on' END
       FROM kill_switches
      WHERE capability IN (p_capability, '*')
        AND ( scope = 'global'
           OR (scope = 'tenant' AND scope_id = p_tenant)
           OR (scope = 'channel_account' AND scope_id = p_channel) )),
    'on')
$$;

CREATE TABLE staff_members (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id        uuid NOT NULL REFERENCES tenants(id),
  platform_user_id text NOT NULL,
  display_name     text NOT NULL,
  role             text NOT NULL CHECK (role IN ('owner','manager','agent','viewer')),
  active           boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, platform_user_id)
);

-- =============================================================================
-- 2. Customers, conversations (handoff state machine), messages
-- =============================================================================

CREATE TABLE customers (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id),
  wa_id        text NOT NULL,                 -- normalized channel identity (do NOT assume it is a phone number)
  phone_e164   text,
  display_name text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, wa_id)
);

CREATE TABLE conversations (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id),
  channel_account_id   uuid NOT NULL REFERENCES channel_accounts(id),
  customer_id          uuid NOT NULL REFERENCES customers(id),
  bot_status           text NOT NULL DEFAULT 'active' CHECK (bot_status IN ('active','paused_human','closed')),
  epoch                integer NOT NULL DEFAULT 0,     -- bumps on every bot_status change; outbound bot replies carry it
  version              integer NOT NULL DEFAULT 0,     -- optimistic lock
  handoff_reason       text,
  assigned_staff_id    uuid REFERENCES staff_members(id),
  needs_turn           boolean NOT NULL DEFAULT false,
  message_seq          bigint NOT NULL DEFAULT 0,      -- per-conversation counter (assigned by trigger)
  last_inbound_seq     bigint NOT NULL DEFAULT 0,
  last_processed_seq   bigint NOT NULL DEFAULT 0,
  summary              text,
  slots                jsonb NOT NULL DEFAULT '{}'::jsonb,   -- cart draft, address draft, size profile, intent...
  last_message_at      timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, channel_account_id, customer_id)
);
CREATE INDEX conversations_needs_turn_idx ON conversations (tenant_id, last_message_at) WHERE needs_turn;

CREATE TABLE messages (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  conversation_id     uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  seq                 bigint NOT NULL,                 -- assigned by trg_messages_seq
  direction           text NOT NULL CHECK (direction IN ('in','out')),
  sent_by             text NOT NULL CHECK (sent_by IN ('customer','bot','staff','automation')),
  staff_id            uuid REFERENCES staff_members(id),
  type                text NOT NULL DEFAULT 'text'
                      CHECK (type IN ('text','image','audio','video','document','location','contact','sticker','reaction','unsupported')),
  body                text,
  media_object_key    text,
  media_type          text,
  location            jsonb,                            -- {lat, lng, name, address} straight from the channel (trusted source)
  provider_message_id text,
  status              text NOT NULL DEFAULT 'received'
                      CHECK (status IN ('received','queued','sent','delivered','read','failed')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (conversation_id, seq)
);
CREATE INDEX messages_conv_seq_idx ON messages (conversation_id, seq DESC);

-- Internal notes live in their own table: no send path ever reads it (structural separation).
CREATE TABLE internal_notes (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  staff_id        uuid NOT NULL REFERENCES staff_members(id),
  body            text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Idempotency at the database level (risk #5): survives a total Redis loss.
CREATE TABLE inbound_events (
  id                  bigserial PRIMARY KEY,
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  channel_account_id  uuid NOT NULL REFERENCES channel_accounts(id),
  provider_message_id text NOT NULL,
  received_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (channel_account_id, provider_message_id)
);

-- Assign messages.seq atomically per conversation, keep the conversation counters in step.
-- The UPDATE takes a row lock on the conversation, which serializes concurrent inserts.
CREATE OR REPLACE FUNCTION app.trg_messages_seq() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_seq bigint;
BEGIN
  UPDATE conversations
     SET message_seq      = message_seq + 1,
         last_inbound_seq = CASE WHEN NEW.direction = 'in' THEN message_seq + 1 ELSE last_inbound_seq END,
         needs_turn       = CASE WHEN NEW.direction = 'in' AND bot_status = 'active' THEN true ELSE needs_turn END,
         last_message_at  = now()
   WHERE id = NEW.conversation_id AND tenant_id = NEW.tenant_id
   RETURNING message_seq INTO v_seq;
  IF v_seq IS NULL THEN
    RAISE EXCEPTION 'conversation % not found for tenant %', NEW.conversation_id, NEW.tenant_id;
  END IF;
  NEW.seq := v_seq;
  -- A human outbound message pauses the bot IN THE SAME TRANSACTION (risk #11).
  IF NEW.direction = 'out' AND NEW.sent_by = 'staff' THEN
    UPDATE conversations
       SET bot_status = 'paused_human', epoch = epoch + 1, version = version + 1,
           handoff_reason = COALESCE(handoff_reason, 'staff_replied')
     WHERE id = NEW.conversation_id AND bot_status = 'active';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER messages_seq BEFORE INSERT ON messages
  FOR EACH ROW EXECUTE FUNCTION app.trg_messages_seq();

-- The ONLY way to change bot_status (column-level grants below forbid direct UPDATE). Optimistic lock.
-- Returns the new epoch, or NULL when the version is stale (caller re-reads and decides).
CREATE OR REPLACE FUNCTION app.set_bot_status(p_conv uuid, p_expected_version integer, p_new_status text,
                                              p_reason text, p_staff uuid DEFAULT NULL)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_epoch integer;
BEGIN
  IF app.current_tenant() IS NULL THEN
    RAISE EXCEPTION 'tenant context required';
  END IF;
  IF p_new_status NOT IN ('active','paused_human','closed') THEN
    RAISE EXCEPTION 'invalid bot_status %', p_new_status;
  END IF;
  UPDATE conversations
     SET bot_status = p_new_status, epoch = epoch + 1, version = version + 1,
         handoff_reason = p_reason, assigned_staff_id = COALESCE(p_staff, assigned_staff_id),
         needs_turn = CASE WHEN p_new_status = 'active' THEN needs_turn ELSE false END
   WHERE id = p_conv AND tenant_id = app.current_tenant() AND version = p_expected_version
   RETURNING epoch INTO v_epoch;
  RETURN v_epoch;   -- NULL => stale version or not this tenant's conversation
END $$;

-- =============================================================================
-- 3. Outbox, scheduled jobs, campaigns, consent, number health (durable queues; risks #5 #6 #17)
-- =============================================================================

CREATE TABLE outbox (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  conversation_id     uuid REFERENCES conversations(id),
  channel_account_id  uuid NOT NULL REFERENCES channel_accounts(id),
  idempotency_key     text NOT NULL UNIQUE,               -- conversation:turn:seq  (a retried turn cannot double-send)
  origin              text NOT NULL CHECK (origin IN ('bot','human','automation')),
  message_class       text NOT NULL CHECK (message_class IN ('service','utility','marketing')),
  expected_epoch      integer,                            -- required for origin='bot'
  to_wa_id            text NOT NULL,
  payload             jsonb NOT NULL,
  status              text NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','sending','sent','failed','dropped_stale','dropped_policy')),
  attempts            integer NOT NULL DEFAULT 0,
  next_attempt_at     timestamptz NOT NULL DEFAULT now(),
  locked_until        timestamptz,
  provider_message_id text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  sent_at             timestamptz,
  CHECK (origin <> 'bot' OR expected_epoch IS NOT NULL)
);
CREATE INDEX outbox_due_idx ON outbox (next_attempt_at) WHERE status IN ('pending','sending');

CREATE TABLE scheduled_jobs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id),
  kind         text NOT NULL,                          -- cart_reminder | review_request | hold_expiry | auto_resume | ...
  dedupe_key   text NOT NULL,                          -- e.g. cart_id:stage1  (one reminder per stage per cart)
  run_at       timestamptz NOT NULL,
  payload      jsonb NOT NULL DEFAULT '{}'::jsonb,
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','done','failed','cancelled')),
  attempts     integer NOT NULL DEFAULT 0,
  locked_until timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, dedupe_key)
);
CREATE INDEX scheduled_jobs_due_idx ON scheduled_jobs (run_at) WHERE status IN ('pending','processing');

CREATE TABLE campaigns (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid NOT NULL REFERENCES tenants(id),
  channel_account_id uuid NOT NULL REFERENCES channel_accounts(id),
  name               text NOT NULL,
  status             text NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft','scheduled','running','paused','completed','cancelled')),
  template           jsonb NOT NULL,                   -- merge-field template; NO per-recipient LLM
  scheduled_at       timestamptz,
  created_by         uuid REFERENCES staff_members(id),
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE campaign_recipients (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id),
  campaign_id uuid NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  customer_id uuid NOT NULL REFERENCES customers(id),
  status      text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sending','sent','failed','skipped')),
  skip_reason text,
  locked_until timestamptz,
  sent_at     timestamptz,
  UNIQUE (campaign_id, customer_id)                    -- a recipient can never be messaged twice by one campaign
);
CREATE INDEX campaign_recipients_pending_idx ON campaign_recipients (campaign_id) WHERE status IN ('pending','sending');

CREATE TABLE consents (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id),
  customer_id uuid NOT NULL REFERENCES customers(id),
  scope       text NOT NULL CHECK (scope IN ('marketing','back_in_stock','review_request','order_updates')),
  granted     boolean NOT NULL,
  source      text NOT NULL,                           -- e.g. 'customer_message','checkout_optin','import'
  evidence    text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ON consents (tenant_id, customer_id, scope, created_at DESC);

CREATE TABLE suppressions (                            -- opt-outs: checked by the Send Policy before every non-service send
  tenant_id   uuid NOT NULL REFERENCES tenants(id),
  customer_id uuid NOT NULL REFERENCES customers(id),
  scope       text NOT NULL,
  reason      text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, customer_id, scope)
);

CREATE TABLE number_health (
  channel_account_id uuid PRIMARY KEY REFERENCES channel_accounts(id),
  tenant_id          uuid NOT NULL REFERENCES tenants(id),
  score              numeric(4,3) NOT NULL DEFAULT 1.000 CHECK (score BETWEEN 0 AND 1),
  daily_cap          integer NOT NULL DEFAULT 50 CHECK (daily_cap >= 0),   -- warm-up ramps this
  sent_today         integer NOT NULL DEFAULT 0,
  day                date NOT NULL DEFAULT current_date,
  state              text NOT NULL DEFAULT 'healthy' CHECK (state IN ('healthy','throttled','paused')),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Cross-tenant claiming for system tasks: SECURITY DEFINER, the only surface sharwa_system may touch.
-- Stale bot replies (epoch changed / conversation no longer 'active') are dropped here, atomically.
CREATE OR REPLACE FUNCTION app.claim_outbox(p_limit integer, p_lease interval DEFAULT interval '60 seconds')
RETURNS SETOF outbox LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  UPDATE outbox o
     SET status = 'dropped_stale'
    FROM conversations c
   WHERE o.conversation_id = c.id
     AND o.status = 'pending' AND o.origin = 'bot'
     AND (c.epoch <> o.expected_epoch OR c.bot_status <> 'active');

  RETURN QUERY
  WITH picked AS (
    SELECT id FROM outbox
     WHERE (status = 'pending' AND next_attempt_at <= now())
        OR (status = 'sending' AND locked_until < now())     -- recover after a crashed dispatcher
     ORDER BY next_attempt_at
     FOR UPDATE SKIP LOCKED
     LIMIT p_limit
  )
  UPDATE outbox o
     SET status = 'sending', attempts = o.attempts + 1, locked_until = now() + p_lease
    FROM picked WHERE o.id = picked.id
  RETURNING o.*;
END $$;

CREATE OR REPLACE FUNCTION app.claim_due_jobs(p_limit integer, p_lease interval DEFAULT interval '120 seconds')
RETURNS SETOF scheduled_jobs LANGUAGE sql SECURITY DEFINER SET search_path = public, pg_temp AS $$
  WITH picked AS (
    SELECT id FROM scheduled_jobs
     WHERE (status = 'pending' AND run_at <= now())
        OR (status = 'processing' AND locked_until < now())
     ORDER BY run_at
     FOR UPDATE SKIP LOCKED
     LIMIT p_limit
  )
  UPDATE scheduled_jobs j
     SET status = 'processing', attempts = j.attempts + 1, locked_until = now() + p_lease
    FROM picked WHERE j.id = picked.id
  RETURNING j.*;
$$;

-- Resolve session -> tenant/channel BEFORE a tenant context exists (ingest). Returns nothing for unknown sessions.
CREATE OR REPLACE FUNCTION app.resolve_session(p_session_id text)
RETURNS TABLE (channel_account_id uuid, tenant_id uuid, engine text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
  SELECT id, tenant_id, engine FROM channel_accounts WHERE session_id = p_session_id
$$;

-- =============================================================================
-- 4. Catalog read model (advisory only: price/stock authority stays with the platform)
--    NOTE: there is deliberately NO cost / margin / wholesale column anywhere (risk #1).
-- =============================================================================

CREATE TABLE catalog_products (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  platform_product_id text NOT NULL,
  title               text NOT NULL,
  description         text,
  category            text,
  attributes          jsonb NOT NULL DEFAULT '{}'::jsonb,
  active              boolean NOT NULL DEFAULT true,
  source_version      bigint NOT NULL,                  -- monotonic; older events are ignored
  updated_at          timestamptz NOT NULL DEFAULT now(),
  search_tsv          tsvector GENERATED ALWAYS AS
                      (to_tsvector('arabic', coalesce(title,'') || ' ' || coalesce(description,''))) STORED,
  UNIQUE (tenant_id, platform_product_id)
);
CREATE INDEX catalog_products_tsv_idx   ON catalog_products USING gin (search_tsv);
CREATE INDEX catalog_products_trgm_idx  ON catalog_products USING gin (title gin_trgm_ops);

CREATE TABLE catalog_variants (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  product_id          uuid NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
  platform_variant_id text NOT NULL,
  sku                 text,
  options             jsonb NOT NULL DEFAULT '{}'::jsonb,      -- {"size":"L","color":"black"}
  price_hint_minor    bigint CHECK (price_hint_minor >= 0),    -- HINT ONLY; never shown without a live check
  currency            char(3) CHECK (currency ~ '^[A-Z]{3}$'),
  stock_hint          integer,
  source_version      bigint NOT NULL,
  UNIQUE (tenant_id, platform_variant_id)
);

-- Hash-partitioned by tenant: a tenant's vectors live in one physical partition together with
-- other tenants' rows only by hash bucket; RLS + exact scan per tenant prevent any cross-tenant neighbour.
-- (Reference uses 8 partitions; production 32-64. Grants exist ONLY on the parent, never on partitions.)
CREATE TABLE catalog_embeddings (
  id           uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id),
  product_id   uuid NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,
  content_hash text NOT NULL,                            -- re-embed only when content changed
  model        text NOT NULL,
  embedding    vector(1024) NOT NULL,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, product_id)
) PARTITION BY HASH (tenant_id);
DO $$
BEGIN
  FOR i IN 0..7 LOOP
    EXECUTE format('CREATE TABLE catalog_embeddings_p%s PARTITION OF catalog_embeddings FOR VALUES WITH (MODULUS 8, REMAINDER %s)', i, i);
  END LOOP;
END $$;

CREATE TABLE kb_chunks (                                 -- store policies (returns/shipping) for kb_search
  id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  source    text NOT NULL,
  content   text NOT NULL,
  tsv       tsvector GENERATED ALWAYS AS (to_tsvector('arabic', content)) STORED
);
CREATE INDEX kb_chunks_tsv_idx ON kb_chunks USING gin (tsv);

CREATE TABLE catalog_sync_cursor (
  tenant_id  uuid PRIMARY KEY REFERENCES tenants(id),
  cursor     text,
  last_event_at      timestamptz,
  last_reconcile_ok  timestamptz                          -- staleness bound (risk #9)
);

-- Deterministic size advisor data (risk #14)
CREATE TABLE size_charts (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid NOT NULL REFERENCES tenants(id),
  name        text NOT NULL,
  scope_type  text NOT NULL CHECK (scope_type IN ('product','category')),
  scope_ref   text NOT NULL,
  fit_type    text NOT NULL DEFAULT 'regular' CHECK (fit_type IN ('slim','regular','oversized')),
  stretch_pct numeric(4,1) NOT NULL DEFAULT 0 CHECK (stretch_pct BETWEEN 0 AND 50),
  version     integer NOT NULL DEFAULT 1,
  UNIQUE (tenant_id, scope_type, scope_ref)
);
CREATE TABLE size_chart_rows (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id  uuid NOT NULL REFERENCES tenants(id),
  chart_id   uuid NOT NULL REFERENCES size_charts(id) ON DELETE CASCADE,
  size_label text NOT NULL,
  sort_order integer NOT NULL,
  height_cm  numrange,
  weight_kg  numrange,
  chest_cm   numrange,
  waist_cm   numrange,
  hips_cm    numrange,
  length_cm  numeric(5,1),
  UNIQUE (chart_id, size_label)
);

-- =============================================================================
-- 5. Back-in-stock: FIFO waitlist + atomic allocation (risk #7)
-- =============================================================================

CREATE TABLE waitlist_entries (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  customer_id         uuid NOT NULL REFERENCES customers(id),
  conversation_id     uuid REFERENCES conversations(id),
  platform_variant_id text NOT NULL,
  status              text NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','held','converted','cancelled','expired')),
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX waitlist_active_uq ON waitlist_entries (tenant_id, customer_id, platform_variant_id)
  WHERE status IN ('waiting','held');
CREATE INDEX waitlist_fifo_idx ON waitlist_entries (tenant_id, platform_variant_id, created_at, id) WHERE status = 'waiting';

CREATE TABLE stock_levels (                              -- last authoritative quantity observed live; also the per-variant serialization point
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  platform_variant_id text NOT NULL,
  observed_available  integer NOT NULL DEFAULT 0 CHECK (observed_available >= 0),
  observed_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, platform_variant_id)
);

CREATE TABLE stock_holds (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  waitlist_entry_id   uuid NOT NULL REFERENCES waitlist_entries(id),
  platform_variant_id text NOT NULL,
  qty                 integer NOT NULL DEFAULT 1 CHECK (qty > 0),
  status              text NOT NULL DEFAULT 'held' CHECK (status IN ('held','converted','expired','released')),
  expires_at          timestamptz NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX stock_holds_one_active_per_entry ON stock_holds (waitlist_entry_id) WHERE status = 'held';
CREATE INDEX stock_holds_variant_idx ON stock_holds (tenant_id, platform_variant_id) WHERE status = 'held';

-- Allocate min(free units, waiters) holds to the OLDEST waiters, atomically.
-- The lock on stock_levels serializes concurrent allocations for the same variant, so
-- sum(active holds) can never exceed the observed available quantity - however many workers race.
-- (Postgres row locks, not Redis: a lost Redis lock cannot cause overselling.)
CREATE OR REPLACE FUNCTION app.allocate_stock_holds(p_variant text, p_available integer, p_ttl interval)
RETURNS SETOF stock_holds LANGUAGE plpgsql AS $$
DECLARE
  v_tenant uuid := app.current_tenant();
  v_active integer;
  v_free   integer;
BEGIN
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'tenant context required'; END IF;
  IF p_available < 0 THEN RAISE EXCEPTION 'p_available must be >= 0'; END IF;

  INSERT INTO stock_levels (tenant_id, platform_variant_id, observed_available)
  VALUES (v_tenant, p_variant, p_available)
  ON CONFLICT (tenant_id, platform_variant_id) DO NOTHING;

  PERFORM 1 FROM stock_levels
   WHERE tenant_id = v_tenant AND platform_variant_id = p_variant FOR UPDATE;

  UPDATE stock_levels SET observed_available = p_available, observed_at = now()
   WHERE tenant_id = v_tenant AND platform_variant_id = p_variant;

  SELECT COALESCE(sum(qty), 0) INTO v_active FROM stock_holds
   WHERE tenant_id = v_tenant AND platform_variant_id = p_variant
     AND status = 'held' AND expires_at > now();

  v_free := GREATEST(p_available - v_active, 0);
  IF v_free = 0 THEN RETURN; END IF;

  RETURN QUERY
  WITH picked AS (
    SELECT id FROM waitlist_entries
     WHERE tenant_id = v_tenant AND platform_variant_id = p_variant AND status = 'waiting'
     ORDER BY created_at, id
     FOR UPDATE SKIP LOCKED
     LIMIT v_free
  ), upd AS (
    UPDATE waitlist_entries w SET status = 'held' FROM picked WHERE w.id = picked.id RETURNING w.id
  )
  INSERT INTO stock_holds (tenant_id, waitlist_entry_id, platform_variant_id, qty, expires_at)
  SELECT v_tenant, upd.id, p_variant, 1, now() + p_ttl FROM upd
  RETURNING *;
END $$;

-- Expire overdue holds; the caller then re-runs allocate_stock_holds so the next in line is promoted.
CREATE OR REPLACE FUNCTION app.expire_stock_holds(p_variant text)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE v_n integer;
BEGIN
  IF app.current_tenant() IS NULL THEN RAISE EXCEPTION 'tenant context required'; END IF;
  WITH e AS (
    UPDATE stock_holds SET status = 'expired'
     WHERE tenant_id = app.current_tenant() AND platform_variant_id = p_variant
       AND status = 'held' AND expires_at <= now()
    RETURNING waitlist_entry_id
  )
  UPDATE waitlist_entries w SET status = 'expired' FROM e WHERE w.id = e.waitlist_entry_id;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END $$;

-- =============================================================================
-- 6. Geography (risk #13): gazetteer + spatial validators. The model never produces coordinates.
-- =============================================================================

CREATE TABLE geo_gazetteer (
  id         bigserial PRIMARY KEY,
  tenant_id  uuid REFERENCES tenants(id),               -- NULL = shared reference data; set = tenant-learned landmark
  level      text NOT NULL CHECK (level IN ('country','governorate','district','area','neighborhood','landmark')),
  name_ar    text NOT NULL,
  name_norm  text NOT NULL,                             -- normalized Arabic (alef/hamza/taa marbuta/diacritics)
  parent_id  bigint REFERENCES geo_gazetteer(id),
  geom       geometry(Geometry, 4326) NOT NULL,
  confidence numeric(3,2) NOT NULL DEFAULT 1.00 CHECK (confidence BETWEEN 0 AND 1)
);
CREATE INDEX geo_gazetteer_geom_idx ON geo_gazetteer USING gist (geom);
CREATE INDEX geo_gazetteer_name_idx ON geo_gazetteer USING gin (name_norm gin_trgm_ops);

CREATE TABLE geo_synonyms (                              -- dialect terms: roundabout / junction / ...
  term_norm text PRIMARY KEY,
  canonical text NOT NULL,
  kind      text NOT NULL
);

-- Returns the governorate containing the point, or NULL if outside every known governorate
-- (=> reject candidate: sea, another country, hallucinated coordinate).
CREATE OR REPLACE FUNCTION app.point_governorate(p_lat double precision, p_lng double precision)
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT id FROM geo_gazetteer
   WHERE level = 'governorate' AND ST_Covers(geom, ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326))
   LIMIT 1
$$;

CREATE TABLE address_resolutions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  conversation_id uuid REFERENCES conversations(id),
  input           jsonb NOT NULL,                        -- pin or free text + extracted entities
  candidates      jsonb NOT NULL DEFAULT '[]'::jsonb,
  decision        text NOT NULL CHECK (decision IN ('accepted','confirm_with_customer','disambiguate','ask_for_pin','rejected')),
  confidence      numeric(3,2) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  source          text NOT NULL CHECK (source IN ('pin','geocoder','gazetteer_centroid')),
  location        geometry(Point, 4326),
  structured      jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  -- a "geocoder"/"gazetteer" fix may only be accepted automatically with a validated point
  CHECK (decision <> 'accepted' OR location IS NOT NULL)
);

-- =============================================================================
-- 7. Money-bearing records, LLM governance, inbox events
--    Money is owned by the platform (decision D3): we store what it returns - BIGINT minor units + ISO currency
--    + a ready-made display string - and never compute, convert or round. No float, no free NUMERIC.
-- =============================================================================

CREATE TABLE checkout_sessions (                          -- what the PLATFORM priced; the only source for amounts shown to customers
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id            uuid NOT NULL REFERENCES tenants(id),
  conversation_id      uuid REFERENCES conversations(id),
  platform_checkout_id text NOT NULL,
  url                  text NOT NULL,
  total_minor          bigint NOT NULL CHECK (total_minor >= 0),
  currency             char(3) NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  display              text NOT NULL,                    -- ready-made amount text FROM THE PLATFORM; shown verbatim (decision D3)
  quote_id             text,                             -- quote locked by the platform (risk #20)
  cart_hash            text NOT NULL,
  idempotency_key      text NOT NULL UNIQUE,
  expires_at           timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, platform_checkout_id)
);

-- Order-tracking identity rule (docs/01 §2.3): same WhatsApp number, OR order number + registered phone together.
-- Attempts are audited; the raw order number of a failed attempt is never stored (only its sha256).
CREATE TABLE order_lookup_attempts (
  id             bigserial PRIMARY KEY,
  tenant_id      uuid NOT NULL REFERENCES tenants(id),
  conversation_id uuid REFERENCES conversations(id),
  customer_id    uuid NOT NULL REFERENCES customers(id),
  path           text NOT NULL CHECK (path IN ('same_number','other_number')),
  order_ref_hash text NOT NULL,
  outcome        text NOT NULL CHECK (outcome IN ('allowed','denied','blocked')),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX order_lookup_denied_customer_idx ON order_lookup_attempts (customer_id, created_at DESC) WHERE outcome = 'denied';
CREATE INDEX order_lookup_denied_order_idx    ON order_lookup_attempts (order_ref_hash, created_at DESC) WHERE outcome = 'denied';

-- Brute-force guard for the "other number" path (RLS scopes the counters to the current tenant):
--   * 3 denied attempts by the same customer identity within 24h  => path closed until the window clears
--   * 5 denied attempts on the same order (any identity) within 24h => that order can only be tracked via staff
CREATE OR REPLACE FUNCTION app.order_lookup_blocked(p_customer uuid, p_order_ref_hash text)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT (SELECT count(*) FROM order_lookup_attempts
           WHERE customer_id = p_customer AND path = 'other_number' AND outcome = 'denied'
             AND created_at > now() - interval '24 hours') >= 3
      OR (SELECT count(*) FROM order_lookup_attempts
           WHERE order_ref_hash = p_order_ref_hash AND outcome = 'denied'
             AND created_at > now() - interval '24 hours') >= 5
$$;

CREATE TABLE llm_calls (
  id              bigserial PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  conversation_id uuid,
  purpose         text NOT NULL CHECK (purpose IN ('router','agent','summary','embedding','classifier','transcribe','other')),
  provider        text NOT NULL,
  model           text NOT NULL,
  input_tokens    integer NOT NULL DEFAULT 0,
  output_tokens   integer NOT NULL DEFAULT 0,
  cost_micro_usd  bigint  NOT NULL DEFAULT 0,
  latency_ms      integer,
  status          text NOT NULL DEFAULT 'ok' CHECK (status IN ('ok','error','timeout','breaker_open')),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX llm_calls_tenant_time_idx ON llm_calls (tenant_id, created_at DESC);

CREATE TABLE tenant_budgets (
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  month           date NOT NULL,
  limit_micro_usd bigint NOT NULL CHECK (limit_micro_usd >= 0),
  used_micro_usd  bigint NOT NULL DEFAULT 0,
  state           text NOT NULL DEFAULT 'ok' CHECK (state IN ('ok','warn_80','degraded','exhausted')),
  PRIMARY KEY (tenant_id, month)
);

CREATE TABLE verifier_blocks (                            -- Output Verifier rejections (risks #8 #12 #20)
  id              bigserial PRIMARY KEY,
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  conversation_id uuid,
  reason          text NOT NULL,                          -- unverified_number | url_not_allowed | secret_pattern | foreign_phone | canary | coord_from_model
  draft_excerpt   text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_counters (
  tenant_id uuid PRIMARY KEY REFERENCES tenants(id),
  inbox_seq bigint NOT NULL DEFAULT 0
);
CREATE TABLE inbox_events (                               -- short-retention log for WebSocket resync by last_seq (risk #18)
  tenant_id  uuid NOT NULL REFERENCES tenants(id),
  seq        bigint NOT NULL,
  type       text NOT NULL,
  payload    jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, seq)
);
CREATE OR REPLACE FUNCTION app.next_inbox_seq() RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE v bigint;
BEGIN
  IF app.current_tenant() IS NULL THEN RAISE EXCEPTION 'tenant context required'; END IF;
  INSERT INTO tenant_counters (tenant_id, inbox_seq) VALUES (app.current_tenant(), 1)
  ON CONFLICT (tenant_id) DO UPDATE SET inbox_seq = tenant_counters.inbox_seq + 1
  RETURNING inbox_seq INTO v;
  RETURN v;
END $$;

-- =============================================================================
-- 8. Row Level Security on EVERY table that carries tenant_id (and is not a partition child)
--    Landmarks learned per tenant: tenant_id IS NULL rows are shared reference data.
-- =============================================================================

DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.relname
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attname = 'tenant_id' AND NOT a.attisdropped
     WHERE n.nspname = 'public' AND c.relkind IN ('r','p') AND NOT c.relispartition
       AND c.relname NOT IN ('geo_gazetteer')
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', r.relname);
    EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id = app.current_tenant()) WITH CHECK (tenant_id = app.current_tenant())', r.relname);
  END LOOP;
END $$;

-- tenants has no tenant_id column (its id IS the tenant): a tenant-scoped session sees only itself.
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_self ON tenants USING (id = app.current_tenant());

-- kill_switches: tenant-scoped role sees global rows + its own tenant/channel rows; system role sees all.
ALTER TABLE kill_switches ENABLE ROW LEVEL SECURITY;
CREATE POLICY ks_app ON kill_switches FOR SELECT TO sharwa_app USING (
  scope = 'global'
  OR (scope = 'tenant' AND scope_id = app.current_tenant())
  OR (scope = 'channel_account' AND scope_id IN (SELECT id FROM channel_accounts))
);
CREATE POLICY ks_system ON kill_switches FOR SELECT TO sharwa_system USING (true);

ALTER TABLE geo_gazetteer ENABLE ROW LEVEL SECURITY;
CREATE POLICY gazetteer_read  ON geo_gazetteer FOR SELECT USING (tenant_id IS NULL OR tenant_id = app.current_tenant());
CREATE POLICY gazetteer_write ON geo_gazetteer FOR INSERT WITH CHECK (tenant_id = app.current_tenant());

-- =============================================================================
-- 9. Grants: least privilege. Partitions are NOT granted (only the parent), so RLS on the parent cannot be bypassed.
-- =============================================================================

GRANT USAGE ON SCHEMA public, app TO sharwa_app, sharwa_system;

DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind IN ('r','p') AND NOT c.relispartition
  LOOP
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO sharwa_app', r.relname);
  END LOOP;
END $$;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO sharwa_app;

-- Handoff state machine (risk #11): bot_status / epoch / version / handoff_reason are writable ONLY through
-- app.set_bot_status() and the messages trigger (both SECURITY DEFINER / owner-context).
REVOKE UPDATE ON conversations FROM sharwa_app;
GRANT UPDATE (summary, slots, needs_turn, last_processed_seq, assigned_staff_id, last_message_at)
  ON conversations TO sharwa_app;
-- The trigger function runs with the caller's rights; make it definer so it may update the protected columns.
ALTER FUNCTION app.trg_messages_seq() SECURITY DEFINER SET search_path = public, pg_temp;

-- Kill switches / tenants / channel_accounts are managed by the admin API, read-only for the tenant-scoped role.
REVOKE INSERT, UPDATE, DELETE ON kill_switches, tenants, channel_accounts FROM sharwa_app;
-- Nothing may erase the audit trail of Output Verifier blocks or LLM calls.
REVOKE UPDATE, DELETE ON verifier_blocks, llm_calls, order_lookup_attempts FROM sharwa_app;

REVOKE ALL ON FUNCTION app.claim_outbox(integer, interval), app.claim_due_jobs(integer, interval),
                       app.resolve_session(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.claim_outbox(integer, interval), app.claim_due_jobs(integer, interval),
                          app.resolve_session(text) TO sharwa_system;
GRANT EXECUTE ON FUNCTION app.current_tenant(), app.effective_switch(uuid, uuid, text),
                          app.set_bot_status(uuid, integer, text, text, uuid),
                          app.allocate_stock_holds(text, integer, interval), app.expire_stock_holds(text),
                          app.point_governorate(double precision, double precision), app.next_inbox_seq(),
                          app.order_lookup_blocked(uuid, text)
      TO sharwa_app;
GRANT SELECT ON kill_switches TO sharwa_system;   -- system tasks read switches directly (no tenant data)
